packages:
    - "modules/svelte-effect-runtime"
    - "modules/svelte-effect-runtime-grammars"
    - "modules/svelte-effect-runtime-language-server"
    - "modules/svelte-effect-runtime-vsix"

allowBuilds:
    "@vscode/vsce-sign": false
    esbuild: true
    keytar: false
    msgpackr-extract: true
    sharp: true

catalog:
    vite: 8.2.0

minimumReleaseAgeExclude:
    - "@sveltejs/adapter-node@6.0.0-next.3"

overrides:
    "@effect/platform-node-shared": "4.0.0-beta.93"
    vite: "catalog:"

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"
