packages:
    - "modules/svelte-effect-runtime"
    - "modules/svelte-effect-runtime-grammars"
    - "modules/svelte-effect-runtime-language-server"
    - "modules/svelte-effect-runtime-vsix"

allowBuilds:
    esbuild: true
    msgpackr-extract: true
    sharp: true

catalog:
    vite: 8.1.3

overrides:
    vite: "catalog:"

peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: "*"
