import type { Plugin, ResolvedConfig, ViteDevServer } from "vite";

const public_module_id = "$ser/env/public";
const private_module_id = "$ser/env/private";
const virtual_prefix = "\0virtual:";
const generated_types_marker = "/** @generated by svelte-effect-runtime */";

type EnvironmentKind = "private" | "public";

interface SvelteKitPluginApi {
	options?: {
		kit?: {
			outDir?: string;
		};
		outDir?: string;
	};
}

type SvelteKitPlugin = Plugin & {
	api?: SvelteKitPluginApi;
};

/** Vite integration for Effect-wrapped SvelteKit environment modules. */
export function make_environment_plugin(): Plugin {
	let environment_types_path: string | undefined;

	return {
		name: "svelte-effect-runtime:environment",
		enforce: "post",

		async configResolved(config) {
			environment_types_path = get_environment_types_path(config);

			await write_environment_types(environment_types_path);
		},

		configureServer(server) {
			watch_environment_types(server, () => environment_types_path);
		},

		resolveId(id) {
			if (id !== public_module_id && id !== private_module_id) {
				return undefined;
			}

			return `${virtual_prefix}${id}`;
		},

		async load(id) {
			if (!id.startsWith(virtual_prefix)) {
				return undefined;
			}

			const source_id = id.slice(virtual_prefix.length);
			const kind = get_environment_kind(source_id);

			if (!kind) {
				return undefined;
			}

			const internal_id = get_sveltekit_environment_id(kind, this.environment.name);
			const resolved = await this.resolve(internal_id, undefined, { skipSelf: true });

			if (!resolved) {
				this.error(`Unable to resolve SvelteKit environment module ${internal_id}.`);
			}

			const loaded = await this.load({ id: resolved.id });
			const names = find_environment_exports(loaded.code ?? "");

			return make_environment_module(kind, names);
		},
	};
}

function get_environment_kind(id: string): EnvironmentKind | undefined {
	if (id === private_module_id) {
		return "private";
	}

	if (id === public_module_id) {
		return "public";
	}

	return undefined;
}

function get_sveltekit_environment_id(kind: EnvironmentKind, environment_name: string): string {
	if (kind === "private") {
		return "__sveltekit/env/private";
	}

	return environment_name === "client"
		? "__sveltekit/env/public/client"
		: "__sveltekit/env/public/server";
}

export function find_environment_exports(code: string): string[] {
	return [...code.matchAll(/\bexport\s+const\s+([A-Za-z_$][\w$]*)\s*=/g)]
		.map((match) => match[1])
		.filter((name): name is string => name !== undefined);
}

export function make_environment_module(kind: EnvironmentKind, names: readonly string[]): string {
	const source_id = `$app/env/${kind}`;
	const imports = [
		`import { Effect } from "effect";`,
		``,
		`import * as environment_values from ${JSON.stringify(source_id)};`,
	];
	const declarations = names.map(
		(name) => `export const ${name} = Effect.succeed(environment_values.${name});`,
	);

	return [...imports, "", ...declarations, ""].join("\n");
}

function get_environment_types_path(config: ResolvedConfig): string {
	const sveltekit = config.plugins.find(
		(plugin): plugin is SvelteKitPlugin => plugin.name === "vite-plugin-sveltekit-setup",
	);
	const options = sveltekit?.api?.options;
	const out_dir = options?.outDir ?? options?.kit?.outDir ?? ".svelte-kit";

	return `${config.root}/${out_dir}/env.d.ts`.replaceAll("\\", "/");
}

function watch_environment_types(
	server: ViteDevServer,
	get_types_path: () => string | undefined,
): void {
	let pending: ReturnType<typeof setTimeout> | undefined;

	server.watcher.on("all", (_event, file) => {
		if (!/(?:^|[/\\])env\.(?:js|ts)$/.test(file)) {
			return;
		}

		if (pending) {
			clearTimeout(pending);
		}

		pending = setTimeout(() => {
			const types_path = get_types_path();

			if (types_path) {
				void write_environment_types(types_path);
			}
		}, 100);
	});
}

async function write_environment_types(path: string): Promise<void> {
	const { readFile, writeFile } = await import("node:fs/promises");

	let content: string;

	try {
		content = await readFile(path, "utf8");
	} catch (error) {
		if (is_missing_file_error(error)) {
			return;
		}

		throw error;
	}

	if (content.includes(generated_types_marker)) {
		return;
	}

	const generated = make_environment_types();

	await writeFile(path, `${content.trimEnd()}\n\n${generated}\n`, "utf8");
}

function is_missing_file_error(error: unknown): boolean {
	return (
		typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT"
	);
}

export function make_environment_types(): string {
	return [
		generated_types_marker,
		`declare module "$ser/env/private" {`,
		`\ttype Source = typeof import("$app/env/private");`,
		`\tconst environment: {`,
		`\t\treadonly [Name in keyof Source]: import("effect").Effect.Effect<Source[Name]>;`,
		`\t};`,
		`\texport = environment;`,
		`}`,
		``,
		`declare module "$ser/env/public" {`,
		`\ttype Source = typeof import("$app/env/public");`,
		`\tconst environment: {`,
		`\t\treadonly [Name in keyof Source]: import("effect").Effect.Effect<Source[Name]>;`,
		`\t};`,
		`\texport = environment;`,
		`}`,
	].join("\n");
}
