import type { Plugin } from "vite";
import { transform_script_effect } from "$/preprocess.ts";
import { transform_markup_effect } from "$/markup/transform.ts";

// ─── Option types ──────────────────────────────────────────────

/**
 * Options for the {@link effect} Vite plugin.
 *
 * @since 2.0.0
 */
export interface EffectOptions {
  /** Whether to emit debug logging in the generated remote client module. */
  debug?: boolean;
}

// ─── Plugin ────────────────────────────────────────────────────

/**
 * Vite plugin for `svelte-effect-runtime`. Injects the effect preprocessor
 * so `<script effect>` and `{yield* expr}` are transformed automatically.
 * In SvelteKit projects it also intercepts `__sveltekit/remote` and
 * generates an Effect-aware client module that wraps query, command, form,
 * and prerender with `Effect`-returning adapters.
 *
 * @example
 * ```ts
 * import { effect } from "svelte-effect-runtime/vite";
 *
 * export default defineConfig({
 *   plugins: [effect()],
 * });
 * ```
 *
 * @since 2.0.0
 * @param options - Optional configuration.
 * @returns A Vite plugin.
 */
export function effect(
  options?: EffectOptions,
): Plugin {

  const resolved_id = "\0@svelte-effect-runtime/remote";

  const effect_preprocess = {
    name: "svelte-effect-runtime",

    markup({ content, filename }: { content: string; filename: string }) {
      const result = transform_markup_effect(content, filename);
      return { code: result.code };
    },

    script({ content, filename }: { content: string; filename: string }) {
      const result = transform_script_effect(content, filename);
      return { code: result.code };
    },
  };

  return {
    name: "svelte-effect-runtime",
    enforce: "pre",

    resolveId(id: string) {
      if (id === "__sveltekit/remote") return resolved_id;
      return undefined;
    },

    load(id: string) {
      if (id !== resolved_id) return undefined;

      return generate_remote_client_module(options);
    },

    transform(code: string, id: string) {
      /** Rewrite imports so .remote.ts files use the server runtime. */
      if (
        id.endsWith(".server.ts") ||
        id.endsWith(".remote.ts") ||
        id.includes("hooks.server.")
      ) {
        const rewritten = code
          .replace(
            /from\s+["']svelte-effect-runtime["']/g,
            `from "svelte-effect-runtime/_server"`,
          )
          .replace(
            /from\s+["']svelte-effect-runtime\/generators["']/g,
            `from "svelte-effect-runtime/_server"`,
          );

        if (rewritten !== code) {
          return { code: rewritten, map: null };
        }
      }

      return undefined;
    },

    config() {
      return {
        optimizeDeps: {
          exclude: ["svelte-effect-runtime"],
        },
        ssr: {
          noExternal: ["svelte-effect-runtime"],
        },
      };
    },

    api: {
      sveltePreprocess: effect_preprocess,
    },
  };
}

/**
 * Generates the inline module code that replaces `__sveltekit/remote`.
 * The generated module imports SvelteKit's internal client remote
 * function modules and wraps each one with the Effect-aware adapter
 * from `svelte-effect-runtime/remote/client`.
 */
function generate_remote_client_module(
  options?: EffectOptions,
): string {

  const debug = options?.debug ?? false;

  return [
    `/**`,
    ` * Auto-generated by svelte-effect-runtime. Do not edit.`,
    ` * Wraps SvelteKit client remote functions with Effect-aware adapters.`,
    ` * @generated`,
    ` */`,
    ``,
    `import {`,
    `  create_remote_query_adapter,`,
    `  create_remote_command_adapter,`,
    `  create_remote_form_adapter,`,
    `} from "svelte-effect-runtime/remote/client";`,
    ``,
    `const base = "__sveltekit";`,
    ``,
    `/** Shared payload decoder. */`,
    `function decode_payload(value) {`,
    `  return value;`,
    `}`,
    ``,
    `/**`,
    ` * Loads a native SvelteKit remote module lazily. The module path is`,
    ` * resolved by Vite's run-time module loader.`,
    ` */`,
    `async function load_native(module_name) {`,
    `  const resolved = await import(module_name);`,
    `  return resolved.default ?? resolved;`,
    `}`,
    ``,
    `export const query_fns = new Map();`,
    `export const command_fns = new Map();`,
    `export const form_fns = new Map();`,
    ``,
    `export async function get_query_fn(id, input) {`,
    `  if (!query_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_query_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    query_fns.set(id, adapter);`,
    `  }`,
    `  return query_fns.get(id)(input);`,
    `}`,
    ``,
    `export async function get_command_fn(id, input) {`,
    `  if (!command_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_command_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    command_fns.set(id, adapter);`,
    `  }`,
    `  return command_fns.get(id)(input);`,
    `}`,
    ``,
    `export async function get_form_fn(id, input) {`,
    `  if (!form_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_form_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    form_fns.set(id, adapter);`,
    `  }`,
    `  return form_fns.get(id)(input);`,
    `}`,
    ``,
    debug
      ? `console.log("[ser] remote client module loaded");`
      : ``,
  ]
    .filter(Boolean)
    .join("\n");
}
