import type { Plugin } from "vite";
import { transform_script_effect } from "$/preprocess.ts";
import { transform_markup_effect } from "$/markup/transform.ts";

/**
 * Options for the {@link effect} Vite plugin.
 *
 * @since 2.0.0
 */
export interface EffectOptions {
  /** Whether to emit debug logging in the generated remote client module. */
  debug?: boolean;
}

/**
 * Svelte preprocessor that lowers `yield*` in script and markup. Drop
 * into `svelte.config.js`:
 *
 * @example
 * ```js
 * import { preprocess } from "svelte-effect-runtime/vite";
 *
 * export default {
 *   kit: { adapter: ... },
 *   preprocess: [preprocess()],
 * };
 * ```
 *
 * @since 2.0.0
 * @returns A Svelte preprocessor group with a `markup` hook.
 */
export function preprocess() {
  return {
    name: "svelte-effect-runtime",

    markup({ content, filename }: { content: string; filename: string }) {
      const sm = find_script(content);

      let combined = content;

      if (sm) {
        const r = transform_script_effect(sm.text, filename);
        if (r.code !== sm.text) {
          combined =
            content.slice(0, sm.open_end) +
            r.code +
            content.slice(sm.close_start);
        }
      }

      const mr = transform_markup_effect(combined, filename);
      return { code: mr.code };
    },
  };
}

/**
 * Vite plugin for SvelteKit. Generates the Effect‑aware remote client
 * module and rewrites `svelte-effect-runtime` imports to `_server` in
 * `.remote.ts` and `.server.ts` files.
 *
 * Pair with {@link preprocess} in `svelte.config.js`.
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { effect } from "svelte-effect-runtime/vite";
 * import { sveltekit } from "@sveltejs/kit/vite";
 *
 * export default defineConfig({ plugins: [effect(), sveltekit()] });
 * ```
 *
 * @since 2.0.0
 * @param options - Optional configuration.
 * @returns A Vite plugin.
 */
export function effect(options?: EffectOptions): Plugin {
  const resolved_id = "\0@svelte-effect-runtime/remote";

  return {
    name: "svelte-effect-runtime",
    enforce: "pre",

    config() {
      return { optimizeDeps: { exclude: ["svelte-effect-runtime"] } };
    },

    resolveId(id: string) {
      if (id === "__sveltekit/remote") return resolved_id;
      return undefined;
    },

    load(id: string) {
      if (id !== resolved_id) return undefined;
      return generate_remote_client_module(options);
    },

    transform(code: string, id: string) {
      if (
        id.endsWith(".server.ts") ||
        id.endsWith(".remote.ts") ||
        id.includes("hooks.server.")
      ) {
        const rewritten = code
          .replace(/from\s+["']svelte-effect-runtime["']/g, `from "svelte-effect-runtime/_server"`)
          .replace(/from\s+["']svelte-effect-runtime\/generators["']/g, `from "svelte-effect-runtime/_server"`);

        if (rewritten !== code) return { code: rewritten, map: null };
      }

      return undefined;
    },
  };
}

function find_script(content: string) {
  const p = /<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi;

  for (const m of content.matchAll(p)) {
    if (m.index !== undefined && !/\bmodule\b/.test(m[1] ?? "")) {
      return {
        text: m[2],
        open_end: m.index + m[0].indexOf(">") + 1,
        close_start: m.index + m[0].lastIndexOf("<"),
      };
    }
  }

  return undefined;
}

function generate_remote_client_module(options?: EffectOptions): string {
  const debug = options?.debug ?? false;

  return [
    `/** Auto-generated by svelte-effect-runtime. Do not edit. */`,
    `import { create_remote_query_adapter, create_remote_command_adapter, create_remote_form_adapter } from "svelte-effect-runtime/remote/client";`,
    `const base = "__sveltekit";`,
    `function decode_payload(value) { return value; }`,
    `async function load_native(name) { const m = await import(name); return m.default ?? m; }`,
    `export const query_fns = new Map();`,
    `export const command_fns = new Map();`,
    `export const form_fns = new Map();`,
    `export async function get_query_fn(id, input) {`,
    `  if (!query_fns.has(id)) {`,
    `    const n = await load_native("/src/routes/" + id.replace(/\\\\./g, "/") + ".server");`,
    `    query_fns.set(id, create_remote_query_adapter(n, decode_payload, base));`,
    `  }`,
    `  return query_fns.get(id)(input);`,
    `}`,
    `export async function get_command_fn(id, input) {`,
    `  if (!command_fns.has(id)) {`,
    `    const n = await load_native("/src/routes/" + id.replace(/\\\\./g, "/") + ".server");`,
    `    command_fns.set(id, create_remote_command_adapter(n, decode_payload, base));`,
    `  }`,
    `  return command_fns.get(id)(input);`,
    `}`,
    `export async function get_form_fn(id, input) {`,
    `  if (!form_fns.has(id)) {`,
    `    const n = await load_native("/src/routes/" + id.replace(/\\\\./g, "/") + ".server");`,
    `    form_fns.set(id, create_remote_form_adapter(n, decode_payload, base));`,
    `  }`,
    `  return form_fns.get(id)(input);`,
    `}`,
    debug ? `console.log("[ser] remote client module loaded");` : "",
  ].filter(Boolean).join("\n");
}
