import type { Plugin } from "vite";
import { transform_script_effect } from "$/preprocess.ts";
import { transform_markup_effect } from "$/markup/transform.ts";

// ─── Option types ──────────────────────────────────────────────

/**
 * Options for the plain Svelte + Vite plugin.
 *
 * @since 2.0.0
 */
export interface SvelteEffectRuntimeOptions {
  /** Passed through to `@sveltejs/vite-plugin-svelte`. */
  svelteOptions?: Record<string, unknown>;
}

/**
 * Options for the SvelteKit-specific plugin.
 *
 * @since 2.0.0
 */
export interface SveltekitEffectRuntimeOptions {
  /** Whether to enable debug logging. */
  debug?: boolean;
}

// ─── Plain Svelte plugin ──────────────────────────────────────

/**
 * Vite plugin for plain Svelte projects (without SvelteKit). Wraps the
 * official Svelte Vite plugin and injects the effect preprocessor so
 * `<script effect>` and `{yield* expr}` in markup are transformed
 * automatically.
 *
 * @example
 * ```ts
 * import { svelte_effect_runtime } from "svelte-effect-runtime/vite";
 *
 * export default {
 *   plugins: [svelte_effect_runtime()],
 * };
 * ```
 *
 * @since 2.0.0
 * @param options - Optional plugin configuration.
 * @returns An array of Vite plugins.
 */
export function svelte_effect_runtime(
  options?: SvelteEffectRuntimeOptions,
): Plugin[] {

  /**
   * The preprocessor that the Vite plugin passes to the Svelte compiler.
   * Uses the name expected by the svelte-hmr convention so HMR works.
   */
  const effect_preprocess = {
    name: "svelte-effect-runtime",

    markup({ content, filename }: { content: string; filename: string }) {
      const result = transform_markup_effect(content, filename);
      return { code: result.code };
    },

    script({ content, filename }: { content: string; filename: string }) {
      const result = transform_script_effect(content, filename);
      return { code: result.code };
    },
  };

  return [
    {
      name: "svelte-effect-runtime",
      enforce: "pre",

      async config() {
        return {
          optimizeDeps: {
            exclude: ["svelte-effect-runtime"],
          },
        };
      },
    },
    {
      name: "svelte-effect-runtime-preprocess",
      enforce: "pre",
      api: {
        sveltePreprocess: effect_preprocess,
      },
    },
  ];
}

// ─── SvelteKit plugin ──────────────────────────────────────────

/**
 * Vite plugin for SvelteKit projects. Intercepts the
 * `__sveltekit/remote` virtual module and generates an Effect-aware
 * client module that wraps SvelteKit's native query, command, form,
 * and prerender with `Effect`-returning adapters.
 *
 * @example
 * ```ts
 * import { sveltekit_effect_runtime } from "svelte-effect-runtime/vite";
 *
 * export default defineConfig({
 *   plugins: [sveltekit_effect_runtime()],
 * });
 * ```
 *
 * @since 2.0.0
 * @param options - Optional configuration.
 * @returns A Vite plugin.
 */
export function sveltekit_effect_runtime(
  options?: SveltekitEffectRuntimeOptions,
): Plugin {

  const resolved_id = "\0@svelte-effect-runtime/remote";

  return {
    name: "sveltekit-effect-runtime",
    enforce: "pre",

    resolveId(id: string) {
      if (id === "__sveltekit/remote") return resolved_id;
      return undefined;
    },

    load(id: string) {
      if (id !== resolved_id) return undefined;

      return generate_remote_client_module(options);
    },

    transform(code: string, id: string) {
      /** Rewrite imports so .remote.ts files use the server runtime. */
      if (
        id.endsWith(".server.ts") ||
        id.endsWith(".remote.ts") ||
        id.includes("hooks.server.")
      ) {
        const rewritten = code
          .replace(
            /from\s+["']svelte-effect-runtime["']/g,
            `from "svelte-effect-runtime/_server"`,
          )
          .replace(
            /from\s+["']svelte-effect-runtime\/generators["']/g,
            `from "svelte-effect-runtime/_server"`,
          );

        if (rewritten !== code) {
          return { code: rewritten, map: null };
        }
      }

      return undefined;
    },

    config() {
      return {
        optimizeDeps: {
          exclude: ["svelte-effect-runtime"],
        },
        ssr: {
          noExternal: ["svelte-effect-runtime"],
        },
      };
    },
  };
}

/**
 * Generates the inline module code that replaces `__sveltekit/remote`.
 * The generated module imports SvelteKit's internal client remote
 * function modules and wraps each one with the Effect-aware adapter
 * from `svelte-effect-runtime/remote/client`.
 */
function generate_remote_client_module(
  options?: SveltekitEffectRuntimeOptions,
): string {

  const debug = options?.debug ?? false;

  return [
    `/**`,
    ` * Auto-generated by svelte-effect-runtime. Do not edit.`,
    ` * Wraps SvelteKit client remote functions with Effect-aware adapters.`,
    ` * @generated`,
    ` */`,
    ``,
    `import {`,
    `  create_remote_query_adapter,`,
    `  create_remote_command_adapter,`,
    `  create_remote_form_adapter,`,
    `} from "svelte-effect-runtime/remote/client";`,
    ``,
    `const base = "__sveltekit";`,
    ``,
    `/** Shared payload decoder. */`,
    `function decode_payload(value) {`,
    `  return value;`,
    `}`,
    ``,
    `/**`,
    ` * Loads a native SvelteKit remote module lazily. The module path is`,
    ` * resolved by Vite's run-time module loader.`,
    ` */`,
    `async function load_native(module_name) {`,
    `  const resolved = await import(module_name);`,
    `  return resolved.default ?? resolved;`,
    `}`,
    ``,
    `export const query_fns = new Map();`,
    `export const command_fns = new Map();`,
    `export const form_fns = new Map();`,
    ``,
    `export async function get_query_fn(id, input) {`,
    `  if (!query_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_query_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    query_fns.set(id, adapter);`,
    `  }`,
    `  return query_fns.get(id)(input);`,
    `}`,
    ``,
    `export async function get_command_fn(id, input) {`,
    `  if (!command_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_command_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    command_fns.set(id, adapter);`,
    `  }`,
    `  return command_fns.get(id)(input);`,
    `}`,
    ``,
    `export async function get_form_fn(id, input) {`,
    `  if (!form_fns.has(id)) {`,
    `    const native = await load_native(`,
    `      "/src/routes/" + id.replace(/\\\\./g, "/") + ".server",`,
    `    );`,
    `    const adapter = create_remote_form_adapter(`,
    `      native,`,
    `      decode_payload,`,
    `      base,`,
    `    );`,
    `    form_fns.set(id, adapter);`,
    `  }`,
    `  return form_fns.get(id)(input);`,
    `}`,
    ``,
    debug
      ? `console.log("[ser] remote client module loaded");`
      : ``,
  ]
    .filter(Boolean)
    .join("\n");
}
