id = "svelte-effect-runtime-language-server"
name = "Svelte Effect Runtime Language Server"
description = "Svelte Effect Runtime language-server support for Svelte files."
version = "3.0.1"
schema_version = 1
authors = ["Barekey"]
repository = "https://github.com/usebarekey/svelte-effect-runtime"

[language_servers.svelte-effect-runtime-language-server]
name = "Svelte Effect Runtime Language Server"
language = "Svelte"
